type: mapping
id: azure_application_gateway_firewall_4002_http_activity_1.1.0
version: '9'
name: Azure Application Gateway Firewall to OCSF class Http Activity
data-types:
- azure-application-gateway-firewall
mapping:
  fields:
    action: (CASE ((0)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Allowed' WHEN 2
      THEN 'Denied' WHEN 99 THEN 'Other' END)::VARCHAR
    action_id: (0)::NUMBER
    activity_id: (0)::NUMBER
    activity_name: (CASE ((0)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Connect'
      WHEN 2 THEN 'Delete' WHEN 3 THEN 'Get' WHEN 4 THEN 'Head' WHEN 5 THEN 'Options'
      WHEN 6 THEN 'Post' WHEN 7 THEN 'Put' WHEN 8 THEN 'Trace' WHEN 99 THEN 'Other'
      END)::VARCHAR
    actor: NULL::VARIANT
    api: NULL::VARIANT
    app_name: (SITE)::VARCHAR
    attacks: NULL::ARRAY
    authorizations: NULL::ARRAY
    category_name: (CASE ((4)::NUMBER) WHEN 4 THEN 'Network Activity' END)::VARCHAR
    category_uid: (4)::NUMBER
    class_name: ('http_activity')::VARCHAR
    class_uid: ('4002')::NUMBER
    cloud: NULL::VARIANT
    connection_info: NULL::VARIANT
    count: NULL::NUMBER
    device: NULL::VARIANT
    disposition: (CASE ((CASE WHEN ACTION IS NULL THEN 0 WHEN ACTION = 'Detected'
      THEN 15 ELSE 99 END)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Allowed' WHEN
      10 THEN 'Exonerated' WHEN 11 THEN 'Corrected' WHEN 12 THEN 'Partially Corrected'
      WHEN 13 THEN 'Uncorrected' WHEN 14 THEN 'Delayed' WHEN 15 THEN 'Detected' WHEN
      16 THEN 'No Action' WHEN 17 THEN 'Logged' WHEN 18 THEN 'Tagged' WHEN 19 THEN
      'Alert' WHEN 2 THEN 'Blocked' WHEN 20 THEN 'Count' WHEN 21 THEN 'Reset' WHEN
      22 THEN 'Captcha' WHEN 23 THEN 'Challenge' WHEN 24 THEN 'Access Revoked' WHEN
      25 THEN 'Rejected' WHEN 26 THEN 'Unauthorized' WHEN 27 THEN 'Error' WHEN 3 THEN
      'Quarantined' WHEN 4 THEN 'Isolated' WHEN 5 THEN 'Deleted' WHEN 6 THEN 'Dropped'
      WHEN 7 THEN 'Custom Action' WHEN 8 THEN 'Approved' WHEN 9 THEN 'Restored' WHEN
      99 THEN 'Other' END)::VARCHAR
    disposition_id: (CASE WHEN ACTION IS NULL THEN 0 WHEN ACTION = 'Detected' THEN
      15 ELSE 99 END)::NUMBER
    dst_endpoint: NULL::VARIANT
    duration: NULL::NUMBER
    end_time: NULL::NUMBER
    end_time_dt: NULL::TIMESTAMP_LTZ
    enrichments: NULL::ARRAY
    firewall_rule: NULL::VARIANT
    http_cookies: NULL::ARRAY
    http_request.url.url_string: (REQUEST_URI)::VARCHAR
    http_response: NULL::VARIANT
    http_status: NULL::NUMBER
    load_balancer: NULL::VARIANT
    malware: NULL::ARRAY
    message: (MESSAGE)::VARCHAR
    metadata.extensions: ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL('name', 'windows',
      'version', '2', 'uid', '1.1.0'))
    metadata.loggers: ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL('version', metadata$dataflow_id))
    metadata.processed_time: (date_part('epoch_milliseconds', metadata$insertion_time::TIMESTAMP_LTZ))::NUMBER
    metadata.processed_time_dt: (metadata$insertion_time)::TIMESTAMP_LTZ
    metadata.product.name: ('azure-application-gateway-firewall')::VARCHAR
    metadata.product.vendor_name: ('azure')::VARCHAR
    metadata.profiles: (ARRAY_CONSTRUCT('cloud','datetime','host','network_proxy','security_control','load_balancer','container','linux/linux_users'))::ARRAY
    metadata.uid: (metadata$uuid)::VARCHAR
    metadata.version: ('1.1.0')::VARCHAR
    observables:
    - name: '''http_request.url'''
      type: '''Uniform Resource Locator'''
      type_id: 23
      reputation: null::VARIANT
      value: null::VARCHAR
    - name: '''http_request.url.url_string'''
      type: '''URL String'''
      type_id: 6
      reputation: null::VARIANT
      value: (REQUEST_URI)::VARCHAR
    - name: '''src_endpoint.hostname'''
      type: '''Hostname'''
      type_id: 1
      reputation: null::VARIANT
      value: (HOSTNAME)::VARCHAR
    - name: '''src_endpoint.ip'''
      type: '''IP Address'''
      type_id: 2
      reputation: null::VARIANT
      value: (CLIENT_IP)::VARCHAR
    proxy: NULL::VARIANT
    proxy_connection_info: NULL::VARIANT
    proxy_endpoint: NULL::VARIANT
    proxy_http_request: NULL::VARIANT
    proxy_http_response: NULL::VARIANT
    proxy_tls: NULL::VARIANT
    proxy_traffic: NULL::VARIANT
    raw_data: NULL::VARCHAR
    severity: (CASE ((0)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Informational'
      WHEN 2 THEN 'Low' WHEN 3 THEN 'Medium' WHEN 4 THEN 'High' WHEN 5 THEN 'Critical'
      WHEN 6 THEN 'Fatal' WHEN 99 THEN 'Other' END)::VARCHAR
    severity_id: (0)::NUMBER
    src_endpoint.hostname: (HOSTNAME)::VARCHAR
    src_endpoint.ip: (CLIENT_IP)::VARCHAR
    src_endpoint.port: (CLIENT_PORT)::NUMBER
    start_time: NULL::NUMBER
    start_time_dt: NULL::TIMESTAMP_LTZ
    status: (CASE ((CASE WHEN ACTION IS NULL THEN 0 WHEN ACTION IN ('Matched', 'Detected')
      THEN 1 ELSE 99 END)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Success' WHEN
      2 THEN 'Failure' WHEN 99 THEN 'Other' END)::VARCHAR
    status_code: NULL::VARCHAR
    status_detail: (DETAILS_MESSAGE)::VARCHAR
    status_id: (CASE WHEN ACTION IS NULL THEN 0 WHEN ACTION IN ('Matched', 'Detected')
      THEN 1 ELSE 99 END)::NUMBER
    time: (date_part('epoch_milliseconds', timestamp::TIMESTAMP_LTZ))::NUMBER
    time_dt: (timestamp)::TIMESTAMP_LTZ
    timezone_offset: NULL::NUMBER
    tls: NULL::VARIANT
    traffic: NULL::VARIANT
    type_name: '(CASE ((400200)::NUMBER) WHEN 400200 THEN ''HTTP Activity: Unknown''
      WHEN 400201 THEN ''HTTP Activity: Connect'' WHEN 400202 THEN ''HTTP Activity:
      Delete'' WHEN 400203 THEN ''HTTP Activity: Get'' WHEN 400204 THEN ''HTTP Activity:
      Head'' WHEN 400205 THEN ''HTTP Activity: Options'' WHEN 400206 THEN ''HTTP Activity:
      Post'' WHEN 400207 THEN ''HTTP Activity: Put'' WHEN 400208 THEN ''HTTP Activity:
      Trace'' WHEN 400299 THEN ''HTTP Activity: Other'' END)::VARCHAR'
    type_uid: (400200)::NUMBER
    unmapped: NULL::VARIANT
