type: mapping
id: citrix_netscalar_application_firewall_logs_4002_http_activity_1.1.0
version: '9'
name: Citrix Netscalar Application Firewall Logs to OCSF class Http Activity
data-types:
- citrix-netscalar-application-firewall-logs
mapping:
  fields:
    action: (CASE ((CASE WHEN ACTION = 'not blocked' THEN 1 WHEN ACTION = 'blocked'
      THEN 2 WHEN ACTION IS NULL THEN 0 ELSE 99 END)::NUMBER) WHEN 0 THEN 'Unknown'
      WHEN 1 THEN 'Allowed' WHEN 2 THEN 'Denied' WHEN 99 THEN 'Other' END)::VARCHAR
    action_id: (CASE WHEN ACTION = 'not blocked' THEN 1 WHEN ACTION = 'blocked' THEN
      2 WHEN ACTION IS NULL THEN 0 ELSE 99 END)::NUMBER
    activity_id: (CASE WHEN METHOD = 'POST' THEN 6 WHEN METHOD = 'GET' THEN 3 WHEN
      METHOD = 'HEAD' THEN 4 WHEN METHOD = 'PUT' THEN 7 WHEN METHOD = 'TRACE' THEN
      8 WHEN METHOD = 'CONNECT' THEN 1 WHEN METHOD = 'DELETE' THEN 2 WHEN METHOD =
      'OPTIONS' THEN 5 WHEN METHOD IS NULL THEN 0 ELSE 99 END)::NUMBER
    activity_name: (CASE ((CASE WHEN METHOD = 'POST' THEN 6 WHEN METHOD = 'GET' THEN
      3 WHEN METHOD = 'HEAD' THEN 4 WHEN METHOD = 'PUT' THEN 7 WHEN METHOD = 'TRACE'
      THEN 8 WHEN METHOD = 'CONNECT' THEN 1 WHEN METHOD = 'DELETE' THEN 2 WHEN METHOD
      = 'OPTIONS' THEN 5 WHEN METHOD IS NULL THEN 0 ELSE 99 END)::NUMBER) WHEN 0 THEN
      'Unknown' WHEN 1 THEN 'Connect' WHEN 2 THEN 'Delete' WHEN 3 THEN 'Get' WHEN
      4 THEN 'Head' WHEN 5 THEN 'Options' WHEN 6 THEN 'Post' WHEN 7 THEN 'Put' WHEN
      8 THEN 'Trace' WHEN 99 THEN 'Other' END)::VARCHAR
    actor: NULL::VARIANT
    api: NULL::VARIANT
    app_name: NULL::VARCHAR
    attacks: NULL::ARRAY
    authorizations: NULL::ARRAY
    category_name: (CASE ((4)::NUMBER) WHEN 4 THEN 'Network Activity' END)::VARCHAR
    category_uid: (4)::NUMBER
    class_name: ('http_activity')::VARCHAR
    class_uid: ('4002')::NUMBER
    cloud: NULL::VARIANT
    connection_info.session.uid: (SESSION_ID)::VARCHAR
    count: NULL::NUMBER
    device: NULL::VARIANT
    disposition: (CASE ((CASE WHEN ACTION = 'not blocked' THEN 1 WHEN ACTION = 'blocked'
      THEN 2 WHEN ACTION IS NULL THEN 0 ELSE 99 END)::NUMBER) WHEN 0 THEN 'Unknown'
      WHEN 1 THEN 'Allowed' WHEN 10 THEN 'Exonerated' WHEN 11 THEN 'Corrected' WHEN
      12 THEN 'Partially Corrected' WHEN 13 THEN 'Uncorrected' WHEN 14 THEN 'Delayed'
      WHEN 15 THEN 'Detected' WHEN 16 THEN 'No Action' WHEN 17 THEN 'Logged' WHEN
      18 THEN 'Tagged' WHEN 19 THEN 'Alert' WHEN 2 THEN 'Blocked' WHEN 20 THEN 'Count'
      WHEN 21 THEN 'Reset' WHEN 22 THEN 'Captcha' WHEN 23 THEN 'Challenge' WHEN 24
      THEN 'Access Revoked' WHEN 25 THEN 'Rejected' WHEN 26 THEN 'Unauthorized' WHEN
      27 THEN 'Error' WHEN 3 THEN 'Quarantined' WHEN 4 THEN 'Isolated' WHEN 5 THEN
      'Deleted' WHEN 6 THEN 'Dropped' WHEN 7 THEN 'Custom Action' WHEN 8 THEN 'Approved'
      WHEN 9 THEN 'Restored' WHEN 99 THEN 'Other' END)::VARCHAR
    disposition_id: (CASE WHEN ACTION = 'not blocked' THEN 1 WHEN ACTION = 'blocked'
      THEN 2 WHEN ACTION IS NULL THEN 0 ELSE 99 END)::NUMBER
    dst_endpoint: NULL::VARIANT
    duration: NULL::NUMBER
    end_time: NULL::NUMBER
    end_time_dt: NULL::TIMESTAMP_LTZ
    enrichments: NULL::ARRAY
    firewall_rule: NULL::VARIANT
    http_cookies: NULL::ARRAY
    http_request.url.hostname: (split_part(split_part(REQUEST, '//', 2), '/', 1))::VARCHAR
    http_request.url.scheme: (split_part(REQUEST, ':', 1))::VARCHAR
    http_request.url.url_string: (REQUEST)::VARCHAR
    http_response: NULL::VARIANT
    http_status: NULL::NUMBER
    load_balancer: NULL::VARIANT
    malware: NULL::ARRAY
    message: (MESSAGE)::VARCHAR
    metadata.extensions: ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL('name', 'windows',
      'version', '2', 'uid', '1.1.0'))
    metadata.loggers: ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL('version', metadata$dataflow_id))
    metadata.processed_time: (date_part('epoch_milliseconds', metadata$insertion_time::TIMESTAMP_LTZ))::NUMBER
    metadata.processed_time_dt: (metadata$insertion_time)::TIMESTAMP_LTZ
    metadata.product.name: ('citrix-netscalar-application-firewall-logs')::VARCHAR
    metadata.product.vendor_name: ('citrix')::VARCHAR
    metadata.profiles: (ARRAY_CONSTRUCT('cloud','datetime','host','network_proxy','security_control','load_balancer','container','linux/linux_users'))::ARRAY
    metadata.uid: (metadata$uuid)::VARCHAR
    metadata.version: ('1.1.0')::VARCHAR
    observables:
    - name: '''http_request.url'''
      type: '''Uniform Resource Locator'''
      type_id: 23
      reputation: null::VARIANT
      value: null::VARCHAR
    - name: '''http_request.url.hostname'''
      type: '''Hostname'''
      type_id: 1
      reputation: null::VARIANT
      value: (split_part(split_part(REQUEST, '//', 2), '/', 1))::VARCHAR
    - name: '''http_request.url.url_string'''
      type: '''URL String'''
      type_id: 6
      reputation: null::VARIANT
      value: (REQUEST)::VARCHAR
    - name: '''src_endpoint.ip'''
      type: '''IP Address'''
      type_id: 2
      reputation: null::VARIANT
      value: (SOURCE)::VARCHAR
    proxy: NULL::VARIANT
    proxy_connection_info: NULL::VARIANT
    proxy_endpoint: NULL::VARIANT
    proxy_http_request: NULL::VARIANT
    proxy_http_response: NULL::VARIANT
    proxy_tls: NULL::VARIANT
    proxy_traffic: NULL::VARIANT
    raw_data: NULL::VARCHAR
    severity: (CASE ((CASE WHEN SEVERITY = 'INFO' THEN 1 WHEN SEVERITY IS NULL THEN
      0 ELSE 99 END)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Informational' WHEN
      2 THEN 'Low' WHEN 3 THEN 'Medium' WHEN 4 THEN 'High' WHEN 5 THEN 'Critical'
      WHEN 6 THEN 'Fatal' WHEN 99 THEN 'Other' END)::VARCHAR
    severity_id: (CASE WHEN SEVERITY = 'INFO' THEN 1 WHEN SEVERITY IS NULL THEN 0
      ELSE 99 END)::NUMBER
    src_endpoint.ip: (SOURCE)::VARCHAR
    src_endpoint.port: (SOURCE_PORT)::NUMBER
    start_time: NULL::NUMBER
    start_time_dt: NULL::TIMESTAMP_LTZ
    status: (CASE ((CASE WHEN ACTION = 'not blocked' THEN 1 WHEN ACTION = 'blocked'
      THEN 2 WHEN ACTION IS NULL THEN 0 ELSE 99 END)::NUMBER) WHEN 0 THEN 'Unknown'
      WHEN 1 THEN 'Success' WHEN 2 THEN 'Failure' WHEN 99 THEN 'Other' END)::VARCHAR
    status_code: NULL::VARCHAR
    status_detail: NULL::VARCHAR
    status_id: (CASE WHEN ACTION = 'not blocked' THEN 1 WHEN ACTION = 'blocked' THEN
      2 WHEN ACTION IS NULL THEN 0 ELSE 99 END)::NUMBER
    time: (date_part('epoch_milliseconds', METADATA$INSERTION_TIME::TIMESTAMP_LTZ))::NUMBER
    time_dt: (METADATA$INSERTION_TIME)::TIMESTAMP_LTZ
    timezone_offset: NULL::NUMBER
    tls: NULL::VARIANT
    traffic: NULL::VARIANT
    type_name: '(CASE ((CASE WHEN METHOD = ''POST'' THEN 400206 WHEN METHOD = ''GET''
      THEN 400203 WHEN METHOD = ''HEAD'' THEN 400204 WHEN METHOD = ''PUT'' THEN 400207
      WHEN METHOD = ''TRACE'' THEN 400208 WHEN METHOD = ''CONNECT'' THEN 400201 WHEN
      METHOD = ''DELETE'' THEN 2 WHEN METHOD = ''OPTIONS'' THEN 400205 WHEN METHOD
      IS NULL THEN 400200 ELSE 400299 END)::NUMBER) WHEN 400200 THEN ''HTTP Activity:
      Unknown'' WHEN 400201 THEN ''HTTP Activity: Connect'' WHEN 400202 THEN ''HTTP
      Activity: Delete'' WHEN 400203 THEN ''HTTP Activity: Get'' WHEN 400204 THEN
      ''HTTP Activity: Head'' WHEN 400205 THEN ''HTTP Activity: Options'' WHEN 400206
      THEN ''HTTP Activity: Post'' WHEN 400207 THEN ''HTTP Activity: Put'' WHEN 400208
      THEN ''HTTP Activity: Trace'' WHEN 400299 THEN ''HTTP Activity: Other'' END)::VARCHAR'
    type_uid: (CASE WHEN METHOD = 'POST' THEN 400206 WHEN METHOD = 'GET' THEN 400203
      WHEN METHOD = 'HEAD' THEN 400204 WHEN METHOD = 'PUT' THEN 400207 WHEN METHOD
      = 'TRACE' THEN 400208 WHEN METHOD = 'CONNECT' THEN 400201 WHEN METHOD = 'DELETE'
      THEN 2 WHEN METHOD = 'OPTIONS' THEN 400205 WHEN METHOD IS NULL THEN 400200 ELSE
      400299 END)::NUMBER
    unmapped: NULL::VARIANT
