type: mapping
id: keycloak_application_logs_3002_authentication_1.1.0
version: '3'
name: Keycloak Application Logs to OCSF class Authentication
data-types:
- keycloak-application-logs
mapping:
  fields:
    activity_id: (CASE WHEN EVENT_TYPE IS NULL THEN 0 WHEN EVENT_TYPE ILIKE '%login%'
      THEN 1 WHEN EVENT_TYPE ILIKE '%logout%' THEN 2 ELSE 99 END)::NUMBER
    activity_name: (CASE ((CASE WHEN EVENT_TYPE IS NULL THEN 0 WHEN EVENT_TYPE ILIKE
      '%login%' THEN 1 WHEN EVENT_TYPE ILIKE '%logout%' THEN 2 ELSE 99 END)::NUMBER)
      WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Logon' WHEN 2 THEN 'Logoff' WHEN 3 THEN 'Authentication
      Ticket' WHEN 4 THEN 'Service Ticket Request' WHEN 5 THEN 'Service Ticket Renew'
      WHEN 99 THEN 'Other' END)::VARCHAR
    actor: NULL::VARIANT
    api.request.uid: (REGEXP_SUBSTR(CORRELATION_ID, 'request_id=([a-z0-9\-]+);', 1,
      1, 'e', 1))::VARCHAR
    auth_protocol: NULL::VARCHAR
    auth_protocol_id: NULL::NUMBER
    category_name: (CASE ((3)::NUMBER) WHEN 3 THEN 'Identity & Access Management'
      END)::VARCHAR
    category_uid: (3)::NUMBER
    certificate: NULL::VARIANT
    class_name: ('authentication')::VARCHAR
    class_uid: ('3002')::NUMBER
    cloud: NULL::VARIANT
    count: NULL::NUMBER
    device: NULL::VARIANT
    dst_endpoint: NULL::VARIANT
    duration: NULL::NUMBER
    end_time: NULL::NUMBER
    end_time_dt: NULL::TIMESTAMP_LTZ
    enrichments: NULL::ARRAY
    http_request: NULL::VARIANT
    is_cleartext: NULL::BOOLEAN
    is_mfa: NULL::BOOLEAN
    is_new_logon: NULL::BOOLEAN
    is_remote: NULL::BOOLEAN
    logon_process.tid: (THREAD_ID)::NUMBER
    logon_type: NULL::VARCHAR
    logon_type_id: NULL::NUMBER
    message: (DESCRIPTION)::VARCHAR
    metadata.extensions: ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL('name', 'windows',
      'version', '2', 'uid', '1.1.0'))
    metadata.loggers: ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL('version', metadata$dataflow_id))
    metadata.processed_time: (date_part('epoch_milliseconds', metadata$insertion_time::TIMESTAMP_LTZ))::NUMBER
    metadata.processed_time_dt: (metadata$insertion_time)::TIMESTAMP_LTZ
    metadata.product.name: ('keycloak-application-logs')::VARCHAR
    metadata.product.vendor_name: ('keycloak')::VARCHAR
    metadata.profiles: (ARRAY_CONSTRUCT('cloud','datetime','host','container','linux/linux_users'))::ARRAY
    metadata.uid: (metadata$uuid)::VARCHAR
    metadata.version: ('1.1.0')::VARCHAR
    observables:
    - name: '''src_endpoint.ip'''
      type: '''IP Address'''
      type_id: 2
      reputation: null::VARIANT
      value: (IP_ADDRESS)::VARCHAR
    - name: '''user'''
      type: '''User'''
      type_id: 21
      reputation: null::VARIANT
      value: null::VARCHAR
    - name: '''user.email_addr'''
      type: '''Email Address'''
      type_id: 5
      reputation: null::VARIANT
      value: (IFF(USER_NAME ILIKE '%@%', USER_NAME, null))::VARCHAR
    - name: '''user.name'''
      type: '''User Name'''
      type_id: 4
      reputation: null::VARIANT
      value: (IFF(USER_NAME NOT ILIKE '%@%', USER_NAME, null))::VARCHAR
    raw_data: NULL::VARCHAR
    service: NULL::VARIANT
    session.uid: (SESSION_ID)::VARCHAR
    severity: (CASE ((CASE WHEN SEVERITY IS NULL THEN 0 WHEN SEVERITY = 'INFO' THEN
      1 WHEN SEVERITY = 'WARN' THEN 3 WHEN SEVERITY = 'ERROR' THEN 5 WHEN SEVERITY
      = 'FATAL' THEN 6 ELSE 99 END)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Informational'
      WHEN 2 THEN 'Low' WHEN 3 THEN 'Medium' WHEN 4 THEN 'High' WHEN 5 THEN 'Critical'
      WHEN 6 THEN 'Fatal' WHEN 99 THEN 'Other' END)::VARCHAR
    severity_id: (CASE WHEN SEVERITY IS NULL THEN 0 WHEN SEVERITY = 'INFO' THEN 1
      WHEN SEVERITY = 'WARN' THEN 3 WHEN SEVERITY = 'ERROR' THEN 5 WHEN SEVERITY =
      'FATAL' THEN 6 ELSE 99 END)::NUMBER
    src_endpoint.ip: (IP_ADDRESS)::VARCHAR
    start_time: NULL::NUMBER
    start_time_dt: NULL::TIMESTAMP_LTZ
    status: NULL::VARCHAR
    status_code: NULL::VARCHAR
    status_detail: NULL::VARCHAR
    status_id: NULL::NUMBER
    time: (date_part('epoch_milliseconds', event_time::TIMESTAMP_LTZ))::NUMBER
    time_dt: (event_time)::TIMESTAMP_LTZ
    timezone_offset: NULL::NUMBER
    type_name: '(CASE ((CASE WHEN EVENT_TYPE IS NULL THEN 300200 WHEN EVENT_TYPE ILIKE
      ''%login%'' THEN 300201 WHEN EVENT_TYPE ILIKE ''%logout%'' THEN 300202 ELSE
      300299 END)::NUMBER) WHEN 300200 THEN ''Authentication: Unknown'' WHEN 300201
      THEN ''Authentication: Logon'' WHEN 300202 THEN ''Authentication: Logoff'' WHEN
      300203 THEN ''Authentication: Authentication Ticket'' WHEN 300204 THEN ''Authentication:
      Service Ticket Request'' WHEN 300205 THEN ''Authentication: Service Ticket Renew''
      WHEN 300299 THEN ''Authentication: Other'' END)::VARCHAR'
    type_uid: (CASE WHEN EVENT_TYPE IS NULL THEN 300200 WHEN EVENT_TYPE ILIKE '%login%'
      THEN 300201 WHEN EVENT_TYPE ILIKE '%logout%' THEN 300202 ELSE 300299 END)::NUMBER
    unmapped: NULL::VARIANT
    user.email_addr: (IFF(USER_NAME ILIKE '%@%', USER_NAME, null))::VARCHAR
    user.name: (IFF(USER_NAME NOT ILIKE '%@%', USER_NAME, null))::VARCHAR
    user.uid: (USER_ID)::VARCHAR
  predicate: EVENT_TYPE ILIKE '%login%' OR EVENT_TYPE ILIKE '%logout%'
