type: mapping
id: netskope_v2_application_events_3002_authentication_1.1.0
version: '1'
name: Netskope V2 Application Events to OCSF class Authentication
data-types:
- netskope-v2-application-events
mapping:
  fields:
    activity_id: (CASE WHEN ACTIVITY IN ('Login Attempt', 'Login Successful', 'Login
      Failed') THEN 1 WHEN ACTIVITY = 'Logout' THEN 2 WHEN ACTIVITY IS NULL THEN 0
      ELSE 99 END)::NUMBER
    activity_name: (CASE ((CASE WHEN ACTIVITY IN ('Login Attempt', 'Login Successful',
      'Login Failed') THEN 1 WHEN ACTIVITY = 'Logout' THEN 2 WHEN ACTIVITY IS NULL
      THEN 0 ELSE 99 END)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Logon' WHEN
      2 THEN 'Logoff' WHEN 3 THEN 'Authentication Ticket' WHEN 4 THEN 'Service Ticket
      Request' WHEN 5 THEN 'Service Ticket Renew' WHEN 99 THEN 'Other' END)::VARCHAR
    actor: NULL::VARIANT
    api: NULL::VARIANT
    auth_protocol: NULL::VARCHAR
    auth_protocol_id: NULL::NUMBER
    category_name: (CASE ((3)::NUMBER) WHEN 3 THEN 'Identity & Access Management'
      END)::VARCHAR
    category_uid: (3)::NUMBER
    certificate: NULL::VARIANT
    class_name: ('authentication')::VARCHAR
    class_uid: ('3002')::NUMBER
    cloud: NULL::VARIANT
    count: NULL::NUMBER
    device.ip: (USER_IP)::VARCHAR
    device.os.type: (CASE ((CASE WHEN DEVICE = 'Android Device' THEN 201 WHEN DEVICE
      = 'iOS Device. iPad' THEN 302 WHEN DEVICE = 'iPhone' THEN 301 WHEN DEVICE =
      'Linux Device' THEN 200 WHEN DEVICE = 'Mac Device' THEN 300 WHEN DEVICE = 'Windows
      Device' THEN 100 WHEN DEVICE IS NULL THEN 0 ELSE 99 END)::NUMBER) WHEN 0 THEN
      'Unknown' WHEN 100 THEN 'Windows' WHEN 101 THEN 'Windows Mobile' WHEN 200 THEN
      'Linux' WHEN 201 THEN 'Android' WHEN 300 THEN 'macOS' WHEN 301 THEN 'iOS' WHEN
      302 THEN 'iPadOS' WHEN 400 THEN 'Solaris' WHEN 401 THEN 'AIX' WHEN 402 THEN
      'HP-UX' WHEN 99 THEN 'Other' END)::VARCHAR
    device.os.type_id: (CASE WHEN DEVICE = 'Android Device' THEN 201 WHEN DEVICE =
      'iOS Device. iPad' THEN 302 WHEN DEVICE = 'iPhone' THEN 301 WHEN DEVICE = 'Linux
      Device' THEN 200 WHEN DEVICE = 'Mac Device' THEN 300 WHEN DEVICE = 'Windows
      Device' THEN 100 WHEN DEVICE IS NULL THEN 0 ELSE 99 END)::NUMBER
    dst_endpoint.ip: (DST_IP)::VARCHAR
    dst_endpoint.location.city: (DST_LOCATION)::VARCHAR
    dst_endpoint.location.coordinates: (array_construct(DST_LATITUDE, DST_LONGITUDE))::ARRAY
    dst_endpoint.location.country: (DST_COUNTRY)::VARCHAR
    dst_endpoint.location.postal_code: (DST_ZIPCODE)::VARCHAR
    dst_endpoint.location.region: (DST_REGION)::VARCHAR
    dst_endpoint.port: (DST_PORT)::NUMBER
    duration: NULL::NUMBER
    end_time: NULL::NUMBER
    end_time_dt: NULL::TIMESTAMP_LTZ
    enrichments: NULL::ARRAY
    http_request.referrer: (REFERER)::VARCHAR
    http_request.uid: (REQUEST_ID)::VARCHAR
    http_request.url.url_string: (URL)::VARCHAR
    http_request.user_agent: (USERAGENT)::VARCHAR
    http_request.version: (split_part(PROTOCOL, '/',2))::VARCHAR
    is_cleartext: NULL::BOOLEAN
    is_mfa: NULL::BOOLEAN
    is_new_logon: NULL::BOOLEAN
    is_remote: NULL::BOOLEAN
    logon_process: NULL::VARIANT
    logon_type: NULL::VARCHAR
    logon_type_id: NULL::NUMBER
    message: NULL::VARCHAR
    metadata.extensions: ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL('name', 'windows',
      'version', '2', 'uid', '1.1.0'))
    metadata.loggers: ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL('version', metadata$dataflow_id))
    metadata.processed_time: (date_part('epoch_milliseconds', metadata$insertion_time::TIMESTAMP_LTZ))::NUMBER
    metadata.processed_time_dt: (metadata$insertion_time)::TIMESTAMP_LTZ
    metadata.product.name: ('netskope-v2-application-events')::VARCHAR
    metadata.product.vendor_name: ('netskope-v2')::VARCHAR
    metadata.profiles: (ARRAY_CONSTRUCT('cloud','datetime','host','container','linux/linux_users'))::ARRAY
    metadata.uid: (metadata$uuid)::VARCHAR
    metadata.version: ('1.1.0')::VARCHAR
    observables:
    - name: '''device'''
      type: '''Endpoint'''
      type_id: 20
      reputation: null::VARIANT
      value: null::VARCHAR
    - name: '''device.ip'''
      type: '''IP Address'''
      type_id: 2
      reputation: null::VARIANT
      value: (USER_IP)::VARCHAR
    - name: '''dst_endpoint.ip'''
      type: '''IP Address'''
      type_id: 2
      reputation: null::VARIANT
      value: (DST_IP)::VARCHAR
    - name: '''http_request.url'''
      type: '''Uniform Resource Locator'''
      type_id: 23
      reputation: null::VARIANT
      value: null::VARCHAR
    - name: '''http_request.url.url_string'''
      type: '''URL String'''
      type_id: 6
      reputation: null::VARIANT
      value: (URL)::VARCHAR
    - name: '''src_endpoint.ip'''
      type: '''IP Address'''
      type_id: 2
      reputation: null::VARIANT
      value: (SRC_IP)::VARCHAR
    - name: '''user'''
      type: '''User'''
      type_id: 21
      reputation: null::VARIANT
      value: null::VARCHAR
    - name: '''user.email_addr'''
      type: '''Email Address'''
      type_id: 5
      reputation: null::VARIANT
      value: (USER)::VARCHAR
    raw_data: NULL::VARCHAR
    service: NULL::VARIANT
    session: NULL::VARIANT
    severity: (CASE ((CASE WHEN SEVERITY = 'low' THEN 2 WHEN SEVERITY = 'medium' THEN
      3 WHEN SEVERITY = 'high' THEN 4 WHEN SEVERITY IS NULL THEN 0 ELSE 99 END)::NUMBER)
      WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Informational' WHEN 2 THEN 'Low' WHEN 3 THEN
      'Medium' WHEN 4 THEN 'High' WHEN 5 THEN 'Critical' WHEN 6 THEN 'Fatal' WHEN
      99 THEN 'Other' END)::VARCHAR
    severity_id: (CASE WHEN SEVERITY = 'low' THEN 2 WHEN SEVERITY = 'medium' THEN
      3 WHEN SEVERITY = 'high' THEN 4 WHEN SEVERITY IS NULL THEN 0 ELSE 99 END)::NUMBER
    src_endpoint.ip: (SRC_IP)::VARCHAR
    src_endpoint.location.city: (SRC_LOCATION)::VARCHAR
    src_endpoint.location.coordinates: (array_construct(SRC_LATITUDE, SRC_LONGITUDE))::ARRAY
    src_endpoint.location.country: (SRC_COUNTRY)::VARCHAR
    src_endpoint.location.postal_code: (SRC_ZIPCODE)::VARCHAR
    start_time: NULL::NUMBER
    start_time_dt: NULL::TIMESTAMP_LTZ
    status: NULL::VARCHAR
    status_code: NULL::VARCHAR
    status_detail: NULL::VARCHAR
    status_id: NULL::NUMBER
    time: (date_part('epoch_milliseconds', event_time::TIMESTAMP_LTZ))::NUMBER
    time_dt: (event_time)::TIMESTAMP_LTZ
    timezone_offset: NULL::NUMBER
    type_name: '(CASE ((CASE WHEN ACTIVITY IN (''Login Attempt'', ''Login Successful'',
      ''Login Failed'') THEN 300201 WHEN ACTIVITY = ''Logout'' THEN 300202 WHEN ACTIVITY
      IS NULL THEN 300200 ELSE 300299 END)::NUMBER) WHEN 300200 THEN ''Authentication:
      Unknown'' WHEN 300201 THEN ''Authentication: Logon'' WHEN 300202 THEN ''Authentication:
      Logoff'' WHEN 300203 THEN ''Authentication: Authentication Ticket'' WHEN 300204
      THEN ''Authentication: Service Ticket Request'' WHEN 300205 THEN ''Authentication:
      Service Ticket Renew'' WHEN 300299 THEN ''Authentication: Other'' END)::VARCHAR'
    type_uid: (CASE WHEN ACTIVITY IN ('Login Attempt', 'Login Successful', 'Login
      Failed') THEN 300201 WHEN ACTIVITY = 'Logout' THEN 300202 WHEN ACTIVITY IS NULL
      THEN 300200 ELSE 300299 END)::NUMBER
    unmapped: NULL::VARIANT
    user.email_addr: (USER)::VARCHAR
  predicate: activity IN ('Login Attempt', 'Login Failed', 'Login Successful', 'Logout')
