type: mapping
id: vmware_nsx_avi_application_logs_4002_http_activity_1.1.0
version: '9'
name: Vmware Nsx Avi Application Logs to OCSF class Http Activity
data-types:
- vmware-nsx-avi-application-logs
mapping:
  fields:
    action: (CASE ((0)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Allowed' WHEN 2
      THEN 'Denied' WHEN 99 THEN 'Other' END)::VARCHAR
    action_id: (0)::NUMBER
    activity_id: (CASE WHEN METHOD IS NULL THEN 0 WHEN METHOD = 'CONNECT' THEN 1 WHEN
      METHOD = 'DELETE' THEN 2 WHEN METHOD = 'GET' THEN 3 WHEN METHOD = 'HEAD' THEN
      4 WHEN METHOD = 'OPTIONS' THEN 5 WHEN METHOD = 'POST' THEN 6 WHEN METHOD = 'PUT'
      THEN 7 WHEN METHOD = 'TRACE' THEN 8 ELSE 99 END)::NUMBER
    activity_name: (CASE ((CASE WHEN METHOD IS NULL THEN 0 WHEN METHOD = 'CONNECT'
      THEN 1 WHEN METHOD = 'DELETE' THEN 2 WHEN METHOD = 'GET' THEN 3 WHEN METHOD
      = 'HEAD' THEN 4 WHEN METHOD = 'OPTIONS' THEN 5 WHEN METHOD = 'POST' THEN 6 WHEN
      METHOD = 'PUT' THEN 7 WHEN METHOD = 'TRACE' THEN 8 ELSE 99 END)::NUMBER) WHEN
      0 THEN 'Unknown' WHEN 1 THEN 'Connect' WHEN 2 THEN 'Delete' WHEN 3 THEN 'Get'
      WHEN 4 THEN 'Head' WHEN 5 THEN 'Options' WHEN 6 THEN 'Post' WHEN 7 THEN 'Put'
      WHEN 8 THEN 'Trace' WHEN 99 THEN 'Other' END)::VARCHAR
    actor: NULL::VARIANT
    api: NULL::VARIANT
    app_name: NULL::VARCHAR
    attacks: NULL::ARRAY
    authorizations: NULL::ARRAY
    category_name: (CASE ((4)::NUMBER) WHEN 4 THEN 'Network Activity' END)::VARCHAR
    category_uid: (4)::NUMBER
    class_name: ('http_activity')::VARCHAR
    class_uid: ('4002')::NUMBER
    cloud: NULL::VARIANT
    connection_info.direction: (CASE ((1)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN
      'Inbound' WHEN 2 THEN 'Outbound' WHEN 3 THEN 'Lateral' WHEN 99 THEN 'Other'
      END)::VARCHAR
    connection_info.direction_id: (1)::NUMBER
    connection_info.protocol_ver: (CASE ((PARSE_IP(CLIENT_IP, 'INET', 1):family)::NUMBER)
      WHEN 0 THEN 'Unknown' WHEN 4 THEN 'Internet Protocol version 4 (IPv4)' WHEN
      6 THEN 'Internet Protocol version 6 (IPv6)' WHEN 99 THEN 'Other' END)::VARCHAR
    connection_info.protocol_ver_id: (PARSE_IP(CLIENT_IP, 'INET', 1):family)::NUMBER
    connection_info.session.uid: (PERSISTENT_SESSION_ID)::VARCHAR
    count: NULL::NUMBER
    device: NULL::VARIANT
    disposition: (CASE ((0)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Allowed' WHEN
      10 THEN 'Exonerated' WHEN 11 THEN 'Corrected' WHEN 12 THEN 'Partially Corrected'
      WHEN 13 THEN 'Uncorrected' WHEN 14 THEN 'Delayed' WHEN 15 THEN 'Detected' WHEN
      16 THEN 'No Action' WHEN 17 THEN 'Logged' WHEN 18 THEN 'Tagged' WHEN 19 THEN
      'Alert' WHEN 2 THEN 'Blocked' WHEN 20 THEN 'Count' WHEN 21 THEN 'Reset' WHEN
      22 THEN 'Captcha' WHEN 23 THEN 'Challenge' WHEN 24 THEN 'Access Revoked' WHEN
      25 THEN 'Rejected' WHEN 26 THEN 'Unauthorized' WHEN 27 THEN 'Error' WHEN 3 THEN
      'Quarantined' WHEN 4 THEN 'Isolated' WHEN 5 THEN 'Deleted' WHEN 6 THEN 'Dropped'
      WHEN 7 THEN 'Custom Action' WHEN 8 THEN 'Approved' WHEN 9 THEN 'Restored' WHEN
      99 THEN 'Other' END)::VARCHAR
    disposition_id: (0)::NUMBER
    dst_endpoint.hostname: (HOST)::VARCHAR
    dst_endpoint.ip: (COALESCE(SERVER_IP, SERVER_NAME))::VARCHAR
    dst_endpoint.port: (SERVER_DEST_PORT)::NUMBER
    duration: NULL::NUMBER
    end_time: NULL::NUMBER
    end_time_dt: NULL::TIMESTAMP_LTZ
    enrichments: NULL::ARRAY
    firewall_rule: NULL::VARIANT
    http_cookies: NULL::ARRAY
    http_request.http_headers: (ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL('name',
      'Authorization', 'value', HEADERS_SENT_TO_SERVER:Authorization)))::ARRAY
    http_request.http_method: (METHOD)::VARCHAR
    http_request.length: (REQUEST_LENGTH)::NUMBER
    http_request.referrer: (REFERER)::VARCHAR
    http_request.url.path: (URI_PATH)::VARCHAR
    http_request.user_agent: (USER_AGENT)::VARCHAR
    http_request.version: (HTTP_VERSION)::VARCHAR
    http_request.x_forwarded_for: (ARRAY_COMPACT(XFF))::ARRAY
    http_response.code: (RESPONSE_CODE)::NUMBER
    http_response.content_type: (RESPONSE_CONTENT_TYPE)::VARCHAR
    http_response.length: (RESPONSE_LENGTH)::NUMBER
    http_status: NULL::NUMBER
    load_balancer.code: (SERVER_RESPONSE_CODE)::NUMBER
    load_balancer.endpoint_connections: (ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL('network_endpoint',
      OBJECT_CONSTRUCT_KEEP_NULL('ip', COALESCE(SERVER_CONN_SRC_IP, VS_IP), 'name',
      VS_NAME, 'port', SERVER_SRC_PORT, 'svc_name', VIRTUALSERVICE))))::ARRAY
    load_balancer.error_message: (SIGNIFICANT_LOG[0])::VARCHAR
    malware: NULL::ARRAY
    message: NULL::VARCHAR
    metadata.extensions: ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL('name', 'windows',
      'version', '2', 'uid', '1.1.0'))
    metadata.loggers: ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL('version', metadata$dataflow_id))
    metadata.processed_time: (date_part('epoch_milliseconds', metadata$insertion_time::TIMESTAMP_LTZ))::NUMBER
    metadata.processed_time_dt: (metadata$insertion_time)::TIMESTAMP_LTZ
    metadata.product.name: ('vmware-nsx-avi-application-logs')::VARCHAR
    metadata.product.vendor_name: ('VMWare')::VARCHAR
    metadata.profiles: (ARRAY_CONSTRUCT('cloud','datetime','host','network_proxy','security_control','load_balancer','container','linux/linux_users'))::ARRAY
    metadata.uid: (metadata$uuid)::VARCHAR
    metadata.version: ('1.1.0')::VARCHAR
    observables:
    - name: '''dst_endpoint.hostname'''
      type: '''Hostname'''
      type_id: 1
      reputation: null::VARIANT
      value: (HOST)::VARCHAR
    - name: '''dst_endpoint.ip'''
      type: '''IP Address'''
      type_id: 2
      reputation: null::VARIANT
      value: (COALESCE(SERVER_IP, SERVER_NAME))::VARCHAR
    - name: '''http_request.url'''
      type: '''Uniform Resource Locator'''
      type_id: 23
      reputation: null::VARIANT
      value: null::VARCHAR
    - name: '''http_request.x_forwarded_for'''
      type: '''IP Address'''
      type_id: 2
      reputation: null::VARIANT
      value: (ARRAY_COMPACT(XFF))::ARRAY
    - name: '''src_endpoint.hostname'''
      type: '''Hostname'''
      type_id: 1
      reputation: null::VARIANT
      value: (HOST)::VARCHAR
    - name: '''src_endpoint.ip'''
      type: '''IP Address'''
      type_id: 2
      reputation: null::VARIANT
      value: (CLIENT_IP)::VARCHAR
    proxy: NULL::VARIANT
    proxy_connection_info: NULL::VARIANT
    proxy_endpoint: NULL::VARIANT
    proxy_http_request: NULL::VARIANT
    proxy_http_response: NULL::VARIANT
    proxy_tls: NULL::VARIANT
    proxy_traffic: NULL::VARIANT
    raw_data: NULL::VARCHAR
    severity: (CASE ((0)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Informational'
      WHEN 2 THEN 'Low' WHEN 3 THEN 'Medium' WHEN 4 THEN 'High' WHEN 5 THEN 'Critical'
      WHEN 6 THEN 'Fatal' WHEN 99 THEN 'Other' END)::VARCHAR
    severity_id: (0)::NUMBER
    src_endpoint.hostname: (HOST)::VARCHAR
    src_endpoint.ip: (CLIENT_IP)::VARCHAR
    src_endpoint.port: (CLIENT_DEST_PORT)::NUMBER
    start_time: NULL::NUMBER
    start_time_dt: NULL::TIMESTAMP_LTZ
    status: (CASE ((CASE RESPONSE_CODE WHEN NULL THEN 0 ELSE IFF(RESPONSE_CODE ILIKE
      '2%', 1, 2) END)::NUMBER) WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Success' WHEN 2
      THEN 'Failure' WHEN 99 THEN 'Other' END)::VARCHAR
    status_code: NULL::VARCHAR
    status_detail: NULL::VARCHAR
    status_id: (CASE RESPONSE_CODE WHEN NULL THEN 0 ELSE IFF(RESPONSE_CODE ILIKE '2%',
      1, 2) END)::NUMBER
    time: (date_part('epoch_milliseconds', report_timestamp::TIMESTAMP_LTZ))::NUMBER
    time_dt: (report_timestamp)::TIMESTAMP_LTZ
    timezone_offset: NULL::NUMBER
    tls: NULL::VARIANT
    traffic: NULL::VARIANT
    type_name: '(CASE ((400200 + (CASE WHEN METHOD IS NULL THEN 0 WHEN METHOD = ''CONNECT''
      THEN 1 WHEN METHOD = ''DELETE'' THEN 2 WHEN METHOD = ''GET'' THEN 3 WHEN METHOD
      = ''HEAD'' THEN 4 WHEN METHOD = ''OPTIONS'' THEN 5 WHEN METHOD = ''POST'' THEN
      6 WHEN METHOD = ''PUT'' THEN 7 WHEN METHOD = ''TRACE'' THEN 8 ELSE 99 END))::NUMBER)
      WHEN 400200 THEN ''HTTP Activity: Unknown'' WHEN 400201 THEN ''HTTP Activity:
      Connect'' WHEN 400202 THEN ''HTTP Activity: Delete'' WHEN 400203 THEN ''HTTP
      Activity: Get'' WHEN 400204 THEN ''HTTP Activity: Head'' WHEN 400205 THEN ''HTTP
      Activity: Options'' WHEN 400206 THEN ''HTTP Activity: Post'' WHEN 400207 THEN
      ''HTTP Activity: Put'' WHEN 400208 THEN ''HTTP Activity: Trace'' WHEN 400299
      THEN ''HTTP Activity: Other'' END)::VARCHAR'
    type_uid: (400200 + (CASE WHEN METHOD IS NULL THEN 0 WHEN METHOD = 'CONNECT' THEN
      1 WHEN METHOD = 'DELETE' THEN 2 WHEN METHOD = 'GET' THEN 3 WHEN METHOD = 'HEAD'
      THEN 4 WHEN METHOD = 'OPTIONS' THEN 5 WHEN METHOD = 'POST' THEN 6 WHEN METHOD
      = 'PUT' THEN 7 WHEN METHOD = 'TRACE' THEN 8 ELSE 99 END))::NUMBER
    unmapped: NULL::VARIANT
